:sourcedir: ../java

= Final, Volatile, Transient - Was, Wozu und Warum?


== Ganz schnell: Transient
`transient` ist ein Marker für Variablen, welche bei einer Serialisierung ignoriert werden sollen. Lange vor Json,
Jackson und `@JsonIgnore`-Annotations konnte man bereits dort Objekte partiell serialisieren.

[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/Transient.java[tags=class]
----


Wird die Transient nun serialisiert und wieder deserialisiert, hat `value2` den Wert `null`.

 Transient{value1='Hallo', value2='Welt'}
 Transient{value1='Hallo', value2='null'}

`transient` klappt übrigens auch wuenderbar mit einer Jackson Json Serialisierung und kann als "native" Alternative
zu `@JsonIgnore` genutzt werden.


== Nun: Final als Konstanten

Final als konstanter Werte. Jede Variable wird nur genau einmal gesetzt und kann nicht überschrieben werden.

[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/FinalConstant.java[tags=aConstantFinalValue]
----


Final im Kontext eines Klassenattributs. Diese können dabei auch und nur im Konstuktor initialisiert werden, da dieser bei jeder
Klasseninstanziierung ausgeführt wird.

[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/FinalConstant.java[tags=constructor]
----

Das war noch recht einfach. Nun als kleine Grundlage für die nächsten Themen:

            
== Das Java Memory Model (JMM)

Das JMM ist eine Abstraktion des darunter liegendenden, plattformabhängigen Hardwaremodells.

 +---------------------------+
 |     Java memory model     |
 +---------------------------+
 +---------------------------+
 |   Hardware memory model   |
 +---------------------------+


Im Modell hat jeder Thread seine eigene Ausführungseinheit und besitzt einen Speichercache. Die Hardware hat hier mit
Level 1, 2 und 3 Caches, Hyperthreading etc. ein wesentlich komplexeres Modell, vor dem uns die JVM ein bisschen schützen will.

    THREAD1                                    THREAD2
+-------------+                            +-------------+
|             |       +------------+       |             |
|  +-------+  |       |    MAIN    |       |  +-------+  |
|  |  CPU  |  |       |   MEMORY   |       |  |  CPU  |  |
|  +-------+  |       |            |       |  +-------+  |
|             |       +------------+       |             |
|  +-------+  |             ║              |  +-------+  |
|  | CACHE |  |             ║              |  | CACHE |  |
|  +-------+  |             ║              |  +-------+  |
|            <══════════════╩═══════════════>            |
+-------------+            bus             +-------------+

Beim Threadstart lädt sich dieser alle notwendigen Daten aus dem Hauptspeicher in seinen Cache und benutzt
zum Abgleich der Daten zwischen Cache und Hauptspeicher zwei Operationen:

* `flush` Änderungen im Cache werden in den Hauptspeicher zurück geschrieben.
* `refresh` Aktuelle Daten aus dem Hauptspeicher wird in den Cache geladen.

Wann `flush` und `refresh` stattfinden bedingen die Regeln des JMM. Das bedeutet für uns, dass Änderungen,
die ein Thread an seinen Daten vornimmt, nicht unbedingt sofort in den Hauptspeicher zurückgeschrieben werden.

Damit stellen sich uns aufgrund dieses Modells einige Fragen:

* _Atomicity_: *Welche Operationen sind atomar, d.h. werden nicht durch andere Threads unterbrochen?* +
             Threads werden unterbrochen um Platz für andere Threads zu machen. Manche Operationen brauchen aber einen
             unterbrechungsfreien Ablauf.

* _Ordering_: *In welcher Reihenfolge passieren die Aktionen?* +
            Die Reihenfolge in der ein Tread seine Aktionen abarbeitet muss nicht zwangsläufig von einem anderen Thread
            in dieser Reihenfolge gesehen werden. Compiler, Optimizer, CPUs machen gerne Reorderings, um performanter
            Aktionen auszuführen. Parzielle flushs, welche nur einen Teil der Änderungen auf einmal postulieren tun
            ihr übrigens.

* _Visibility (Sequential Consistency)_: *Wann werden Modifikationen im Speicher anderen Threads sichtbar gemacht?*
            Durch die `flush` und `refresh` Operationen, sehen andere Threads Änderungen an gemeinsam genutzten Variablen
            ggf. sehr viel später.


Beispiele:
[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/JmmPitfalls.java[tags=jmm]
----

* `number`: Ein long mit 64bit Länge. Auf 32 bit Systemen kann es passieren, dass beim Lesen nur die Hälfte des Werts
          gesetzt ist. -> _Atomicity_
* `flag`: Die JVM garantiert uns für ein Boolean immer einen atomaren Zugriff. Soweit so gut.
          Problem gelöst! Allerdings ist hier noch lange nicht gesagt, dass der Wert auch aus dem Cache von `Thread1`
          geflusht wurde. `Thread2` kann noch immer `false`sehen. -> _mangelnde Sequential Consistency_
* `read`: Die Methode geht davon aus, dass zuerst die long-Variable und dann erst das flag auf true gesetzt wurde.
          Wenn also die Bedingung erfüllt ist, geben wir immer den richtigen Wert auf der Konsole aus? Oh... Doch nicht.
          Beim Flush von `Thread1` in den Hauptspeicher und dem refresh von `Thread2` kann es passieren, dass beide
          Anweisungen gedreht werden, sodass `flag` bereits `true` ist, number aber noch `0L` -> _Reordering_


== Final im nebenläufigen Umfeld

In folgender Klasse werden zwei Werte definiert. Eine ist final, die andere nicht. Im ersten Thread und damit in seinem
Cache wird der Konstruktor aufgerufen und die Werte gesetzt.

`Thread2` wiederum hat nun das Problem der _Sequential Consistency_. Aber wann werden jetzt die Variablen `f`, `x` und
`y` von Thread1 in den Hauptspeicher geflusht? Für `f` ist es dabei noch relativ egal. Aber wenn wir beim Auslesen in
`Thread2` auf einmal `f` sehen, `x` und `y` aber noch nicht geflusht wurden, kann es zu unvorhergesehenen Ereignissen kommen.

Hier hilft nun das `final`. Da einer `final`-Varible nur einmal ein Wert zugewiesen werden kann, wird bei genau dieser
Zuweisung ein partierller `flush` ausgeführt und die Variable wird im gesamten Speicher propagiert.
Für `Thread2` bedeutet das, wannimmer ein lesender Zugriff auf eine `final`-Variable geschieht, gearaniert und das JMM,
dass der Wert aktuell und korrekt ist.

[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/FinalConcurrent.java[tags=class]
----

== Volatile - Der kleine Bruder von synchronized

[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/Volatile.java[tags=class]
----



