:sourcedir: ../java

= Teil 2 : Das Java Typsystem und wo es sich nur für eins hält.

Wie bei jeder anderen höheren Programmiersprache, so hampelt man auch bei Java nicht mehr direkt auf den Speicherblöcken des
Rechners herum, sondern hat eine Abstraktion, welche einem die Arbeit erleichert. Damit nun aber die einzelnen Bytes richtig
interpretiert werden können, benötigen wir Typen und ein Typsystem.

== Primitive und Literale
Java bezeichnet sich selbst zwar als objektorientierte Sprache, ganz genau stimmt das aber nicht. Neben den eigentlichen
Objekten, besitzt Java ebenfalls Primitivtypen, wie `int`, `double` und `char`, welche weder Methoden besitzen, noch
andere Attribute als ihren inhärenten Wert.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Primitives.java[tags=without_class]
----

Eine Sonderrolle nehmen dabei Arrays ein. Arrays bilden die einzige native Collection, welche direkt in der JVM abgebildet
wird, also nicht mit Sprachkonstrukten nachgebaut wird. Arrays speichern neben eigentlichen Werten auch immer den Typ
mit, um den Speicherverbrauch für die JVM berechnen zu können.

== Autoboxing
Neben jedem Primitivtyp existiert eine dazugehörige Wrapperklasse, welche z.B ein `int` etwas objektorientieter macht und
so zum Beispiel für Collectionklassen oder generell für Generics verfügbar macht.

Seit Java 5 muss man auch die
Primitivtypen nicht mehr explizit auf diese Wrapperklassen casten, sondern kann sich diese Aufgabe vom Javacompiler
übernehmen lassen:


[source,java]
----
include::{sourcedir}/deepdive/typesystem/Primitives.java[tags=autoboxing]
----
Dabei ist es unerheblich, ob man die Zuweisung zu einer Variable oder den Wert als Parameter einer Methode übergibt.

*Aber*: Das Autoboxing ist leider nicht ganz zu Ende gedacht. Schaut man sich folgendes Beispiel an, so würde man
erwarten, dass das `2` Literal wie im oberen Beispiel zu einem `Integer` konvertiert und sodann an den `instanceof`
Operator übergeben wird. Dem ist aber nicht so. Literale bleiben in dieser Konstruktion immer ihrem Primitivtyp treu.
Hier wird also `false` ausgegebem.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Primitives.java[tags=autoboxing_strange]
----

== Klassen
Hier wird es objektorientiert.

Der Kern des Java Typsystems besteht aus Klassen und Objekten und die Beziehungen und Hierarchien dazwischen. Als
Basis gilt die von allen Klassen abgeleitete Oberklasse `Object`. Ein allen Klassen gemeinsamer Bottomtype existiert nicht.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Classes.java[tags=classes]
----

Hier sehen wir auch direkt wieder eine Besonderheit bei den Literalen. Ein Stringliteral ist immer vom Typ `String`,
also ein Objekt. So ist denn auch folgender Ausdruck valide `"Hallo".toString()` und auch das vorangegangene Beispiel
klappt mit einem Stringliteral `"Hallo" instanceof Object`.

== Was ist mit null und void ?

In jedem formalen System ist es meist förderlich immer auch das Nullelement zu definieren. In der Mathematik kamen
als erstes die arabischen Gelehrten auf die Idee, mit der uns heute selbstverständlichen `0` die Leere zu formalisieren.
Ein damals nicht alltäglicher Begriff, schaut man sich zum Beispiel das römischen Zahlensystem an, in dem man ein leeres
Element vergeblich sucht. Auch in formalen Sprachen ist es daher sinnvoll, ein leeres oder Nullelement zu definieren, um
die Nichtexistenz eines Elements zu signalisieren. In Java gibt es dafür die zwei Schlüsselwörter: `null` und `void`.

=== null
`null` ist die Nullreferenz. Ein Ausdruck `Object o = null;` definiert also eine Referenz `o`, welche auf `null` zeigt, also
keinen Wert besitzt. Leider war das eine nicht ganz durchdachte Entscheidung der Javaväter und -mütter. Millionen und Abermillionen
Zeilen `if(o != null)` sind somit entstanden. Modernere Konzepte wie `Optional`-Monaden oder Kotlins `nullable`-Types versuchen
diesem Problem Herr zu werden.

Aber was ist nun `null` eigentlich? Betrachtet man `null` vom Typsystem aus, so fragt man sich, welchen Platz `null` darin einnimmt.
Eine `0` ist ja eine Zahl wie `1` oder `2`. Eine leere Menge `{}` ist genauso eine Menge wie `{'Apfel', 'Birne'}` und alle
Operationen aus ihrem jeweiligen System lassen sich auf sie anwenden. `0 + 1` ist ebenso valide wie `{} ∪ {'Apfel'}`.


Nun. `null` ist schon mal kein Primitivtyp. Folgender Ausdruck ist daher nicht gültig:
[source,java]
----
include::{sourcedir}/deepdive/typesystem/NullAndVoid.java[tags=null_not_a_primitive]
----


Wenn `null` nun also kein Primitivtyp ist, ist es dann eine Art Objekt? Also vielleicht ein Nullobjekt, welches
auf jede Referenz passt?

[source,java]
----
include::{sourcedir}/deepdive/typesystem/NullAndVoid.java[tags=null_not_an_object]
----
Leider zeigt sich auch hier, dass `null` auch kein Obekt ist. Eine Referenz vom Typ `Objekt`, die den Wert
`null` enthält, ist kein Objekt. `null` ist also ganz simpel eine Nullreferenz und ist leider mit dem Typsystem
nicht zu vereinen.

=== Void

Anders als `null` findet man das Wort `void` oft als Rückgabetypen von Methoden vor und auch nur dort kann es
der Syntax her eingesetzt werden. Allerdings haben hier die Javaentwickler daneben eine `Void`-Klasse eingeführt
mit der etwas unbefriedigenden Beschreibung:

  The {@code Void} class is an uninstantiable placeholder class to hold a
  reference to the {@code Class} object representing the Java keyword
  void.

Und tatsächlich lässt sich der Typ z.B. als Generic benutzen, wobei als "Wert" sich hier nur `null` übergeben lässt.
Generell lässt sich von `Void` keine Instanz erzeugen, da es einen privaten Konstruktor besitzt. Ein Singletonobjekt
existiert nicht.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/NullAndVoid.java[tags=void_as_generic]
----

Wer nun aber vermutet, dass `Void` und `void` sich wie `Integer` und `int` verhalten, der wird leider enttäuscht.
`Void` kann nicht `void` sein. Dafür aber `null`. Klingt komisch...  ;-)

[source,java]
----
include::{sourcedir}/deepdive/typesystem/NullAndVoid.java[tags=void_type]
----

Aus Sicht des Typsystems können wir also abschließend sagen, dass weder `void` noch `null` wirklich Mitglieder in diesem
System sind. Einzig die Klasse `Void` ist Bestandteil des Typsystems, auch wenn sie in Java nicht instantiiert werden kann
und keinen Bezug zu seinem Namensvetter `void` hat. Ein Beispiel aus Groovy, welches sich nicht um private Konstruktoren
schert, zeigt, dass auch ein `Void` ein `Object` ist.

[source,groovy]
----
include::{sourcedir}/deepdive/typesystem/NullAndVoid.java[tags=void_is_an_object]
----

== Generics, oder parametrische Polymorphie
Bis Java 5 war die Collections-API sehr generisch und lediglich auf `Object` beschränkt. Eine Liste konnte also faktisch
alle Objekte aufnehmen, die irgendwie von `Object` abgeleiten waren.
Wollte man Objekte aus einer Liste lesen, musste man immer einen expliziten Typecast vollziehen. Was bei unbekannten
Listen gerne auch mal in einer ClassCastException endete:

[source,groovy]
----
include::{sourcedir}/deepdive/typesystem/Generics.java[tags=old_lists]
----

Um diesem Problem zu begegnen, führte Sun 2004 unter der Leitung von Martin Odersky (Der Typ, der Scala erfunden hat ;-) )
mit der Version 5 die "Java Generics" ein. Der bis dahin größte Umbau im Java Typsystem.

Typen können seitdem zu "generischen" oder "parametrisch polymorphen" Typen avan­cie­ren indem sie selbst noch einmal
einen weiteren Typ als Parameter annehmen können.

=== type arguments
Als Beispiel soll hier der Typ `List` dienen. Im folgenden Beispiel erzeugen wir zwei Referenzen von `List` die jeweils
einen anderen Parametertyp enthalten. `String` und `Integer`. Gelesen als `List of String`.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Generics.java[tags=generics_in_use]
----

Auch wenn beide Ausdrücke als Basistyp `List` haben, handelt es sich um zwei komplett verschiedene Typen, die sich nicht
kombinieren lassen. Eine `List<String>` ist eben keine `List<Integer>`.

Und selbst wenn die Parametertypen von zwei Referenzen in einer gemeinsamen Hierachie existieren, so sind es die
daraus entstandenen parametrisierten Typen nicht.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Generics.java[tags=generic_type_not_polymorphic]
----

Eine `List<String>` ist auch keine `List<Object>`, obwohl ein `String` ein `Object` ist! Das trotzdem eine Hierarchie
in den generischen Typen existiert und wie diese aussieht, wird später behandelt.


=== typed classes

Typparameter sind nicht nur auf Referenzen beschränkt, sondern durchziehen das gesamte Typsystem von Java. Im folgende
Beispiel erzeugen wir eine starre Integer-Liste, indem von `ArrayList` geerbt wird und dieser Typ dabei mit `Integer`
parametrisiert wird.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Generics.java[tags=typed_class]
----

=== generic classes

Um nun eine eigene generische Klasse zu schreiben, bedarf es lediglich eines Typparameters, direkt hinter unserem
Typbezeichner. Wie im unteren Beispiel gezeigt, bauen wir uns einen `ElementAdder`, der einen Typparameter vom Namen
`E` mitbringt, welcher den Typ unserer Elemente darstellen soll.

Diesen Typparameter können wir nun, wie jeden anderen Typ als Parameter, Rückgabewerte oder auch wieder als
Typparameter in anderen generischen Klassen einsetzen. Im Beispiel sehen wir die Methode `addElement`, welche
als Parameter eine List of `E` und ein Element des Typs `E` übergeben bekommt und wiederum eine List of `E`
zurück gibt.


[source,java]
----
include::{sourcedir}/deepdive/typesystem/Generics.java[tags=generic_class]
----

Möchten wir nun unsere Klasse benutzen, so tun wir dies wie in den anderen Beispielen, indem wir bei der Instanziierung
einen Typ als Paramter mitgeben, der dann unseren Parameter `E` ersetzt.

Im ersten Beispiel, erzeugen wir uns einen String Adder. Dieser kann Listen of `String` weitere `String` s hinzufügen.
Die zweite Instanz wiederum ist ein Double Adder. Dieser Adder kann Listen of `Double` weitere `Double` Elemente
hinzufügen.

=== typed methods

Generics sind nicht nur Klassen vorbehalten. Man kann in Java auch generische Methoden erzeugen. Also Methoden, die
erst beim Aufruf einen Typbezeichner erhalten, den sie in ihrer internen Logik benutzen sollen.

Im folgenden Beispiel haben wir so eine generische Methoden. Den generischen Typ einer Methode findet man noch vor
dem Rückgabetyp in spitzen Klammern. `addElement` erhält den Typparameter `E`, der sich als Parameter des Rückgabetyps
findet, wie auch in den Parametern.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Generics.java[tags=typed_methods]
----

Möchte man die Methoden nutzen, so übergibt man den Paramtertypen entweder explizit vor dem eigentlichen Methodennamen:
`this.<String>addElement(stringList, "Hallo Welt");`. Mit dem Aufruf können wir `addElement` nun dazu bringen, einer
`List<String>` einen neuen `String` zuzuweisen und die Liste als `List<String>` wieder zurückzugeben.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Generics.java[tags=typed_methods_usage]
----

Damit wir nicht jedes mal den Typ explizit setzen müssen, bietet Java einen type inference Mechanismus an, wodurch
der Compiler den Parametertyp anhand der übergebenen Werte oder der Zielvariable des Rückgabewerts ermittelt.

Im oberen Beispiel ermittelt der Compiler den Wert des Typparameters `E` anhand der übergebenen Werte. Wenn also der
erste Parameter der Methode eine `List<E>` ist, wir der Methode ein `List<Integer>` geben, so ermittelt der Compiler für
`E` sofort den Typ `Integer`.


== Advanced Generics

Nachdem wir uns nun die generic types in Java angesehen haben, tauchen wir wieder ein wenig tiefer in die JVM ein
und schauen uns an, wie die Typparameter auf Bytecodeebend behandelt werden. Hier entdecken wir direkt einen Unterschied
zwischen der Compilezeit und der Laufzeit des fertigen Bytecodes.

=== statische und dynamische Typen

Um das Verhalten der Generics in der JVM besser verstehen zu können, 

=== type erasure

Generic types wurden als Erweiterung für den Compiler eingeführt, um eine verbesserte Typüberprüfung im Code
zu ermöglichen und somit vor allem Fehler beim Entwickeln zu vermeiden.
Generics waren daher von jeher eine reine Erweiterung des Compiler, weniger der JVM und beeinflussen den
aus Java generierten Bytecode nur sehr wenig.



Tatsächlich werden alle Informationen über parametrisierte Typen aus dem Bytecode entfernt. Dieses Vorgehen nennt sich
`type erasure`

[source,java]
----
include::{sourcedir}/deepdive/typesystem/TypeErasure.java[tags=type_erasure]
----

     -- javap -c TypeErasure
     void typeErasure();
         Code:
            0: new           #5                  // class java/util/ArrayList
            3: dup
            4: invokespecial #6                  // Method java/util/ArrayList."<init>":()V
            7: astore_1
            8: new           #5                  // class java/util/ArrayList
           11: dup
           12: invokespecial #6                  // Method java/util/ArrayList."<init>":()V
           15: astore_2
           16: return


=== Non-Reifiable Types






=== Advanced
    src/main/java/deepdive/typesystem/AdvancesGenerics.java:10: error: incompatible types: List<String> cannot be converted to List<Object>
            List<Object> objList = strList;



==== Liskovsche Substitutionsprinzip
http://www.nils-haldenwang.de/german/das-liskovsche-substitutionsprinzip-in-java-invarianz-kovarianz-kontravarianz

==== Wildcard