:sourcedir: ../js

= Teil 3 : Funktionale Programmierung

Die funktionale Programmierung ist eine der großen Stömungen in der Informatik, die sehr oft gegensätzlich zur
imperativen Programmierung angesehen wird. Und tatsächlich sind die Beweggründe der Entstehung sehr konträr.

Während die imperativen Programmiersprachen zu Anfang von Ingenieuren und Physikern entwickelt wurden, um nicht immer die
Bits einzeln in das Register zu laden, entwickelte sich die funktionale Programmierung aus der mathematischen Richtung,
als die Mathematiker erkannten, welches Potential in den aufkommenden elektronischen Rechner steckte.

So entwickelten sich die imperativen Sprachen von ersten Mnemocode-Schnipseln über C und C++ zu moderneren Varianten wie
Java, C# und Go. Die Sprachen abstrahierten dabei immer weiter die darunter liegende technische Schicht und betteten
immer weitere Komfortfeatures ein.

Auf der funktionalen Ebene ging es genau andersherum. Mit dem Lambdakalkül wurde um 1936 zunächst eine formale und mathematische
Basis der funktionalen Programmierung gelegt und mit dem aufkommen der ersten brauchbaren Rechner um 1960 mit Lisp zur
ersten sich durchsetzenden Sprache umgesetzt. Das die Entwickler hier bereits von einer viel höheren Abstraktion kamen
und möglichst nicht viel tiefer in die Technik einsteigen wollten, merkt man an den bereits damals vorhandenen
Komfortfeatures wie der automatischen Speicherreservierung- und bereinigung. Die imperativen Entwickler mussten hier noch
ein paar Jahre warten bis Java mit der virtuelle Maschine daherkam.

Beide Welten kamen sich mit der Zeit immer näher. So basiert z.B. unser heutiges Verständnis der
objektorientierten Programmierung größtenteil auf den Lisp Flavors. Doch blieb der Kernaspekt der funktionalen
Programmierung, das Lambdakalkül, immer reiner Teil der funktionalen Programmiersprachen.

In letzter Zeit flossen die beiden Hauptströmungen nun aber mehr und mehr zusammen und auch die Konstrukte rund um das
Lambdakalkül hielten in die modernen Vertreter der Sprachen ein. Die erste Sprache auf der JVM war Scala, welche
für sich beanspruchte, die Objektorientierung und die funktionale Sprache ganzheitlich zu vereinen.

Neue Sprachen wie Swift liefern direkt die Unterstützung für Funktionen als first class citizen etc. Und selbst die alte
Tante Java hatte das Zeichen der Zeit erkannt und mit Java 8 hielten denn auch Lamdaausdrücke in die Sprache ein.


== Values vs. Variables

Aus imperativen Sprachen kennen wir Variablen als einen benamten, definierten Speicherbereich, der Werte aufnehmen kann.
Der Speicherbereich ist dabei aber nicht fest, sondern kann jederzeit überschrieben werden.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/ValuesAndVariables.js[tags=imperative]
----

Die funktionale Welt kennt keine Variablen, sondern nur Werte (z.B. `5`) und Funktionen, die lediglich einen Namen
bekommen. Werte sind immer fest und können nicht geändert, sondern nur zur Berechnung herangezogen werden.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/ValuesAndVariables.js[tags=functional]
----

Während also bei imperativen Sprachen zunächst der Speicherbereich definiert und dann mit Werten gefüllt wird,
so wird bei funktionalen Sprachen zunächst ein Wert definiert und ihm dann erst ein Name zugewiesen.

NOTE: __Unter der Haube läuft es natürlich wieder auf Speichermanipulationen hinaus, aber das weiß ja die Sprache nicht.__

== Was ist eine Funktion?

Da die funktionale Programmierung sich ursprünglich aus der Mathematik entwicklet hat, so sind
auch die Funktionen in solchen Sprachen denen der Mathematik eng verbunden.

Eine Funktion hat immer:

* einen oder mehrere Eingabeparameter
* ein Ergebnis auf Basis der Parameter

[source,javascript]
----
include::{sourcedir}/deepdive/functional/ToBeOrNotToBeAFunction.js[tags=a_function]
----

Wichtig beim letzten Punkt ist die Einschränkung auf die Eingabeparameter. Funktionen, welche Effekte
außerhalb des Ergebnis haben, bzw. deren Ergebnis von anderen Faktoren, als den Parametern beeinflusst
werden, heißen seiteneffektbehaftet und gelten im strengen Sinne nicht als Funktionen.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/ToBeOrNotToBeAFunction.js[tags=not_a_function]
----

`setY` ist keine Funktion, da sie kein Ergebnis zurück liefert und als Seiteneffekt eine Variable
außerhalb ihres Funktionskörpers ändert.

`sideEffectFunction` ist ebenfalls keine Funktion, da sie `x` auf einem anderen Kanal als dem
Rückgabewert ausgibt und darüber hinaus ihr Ergebnis von `y` beeinflusst wird, welches nicht Teil
ihrer Parameterliste ist.


NOTE:  __Wie trotz dieser Einschränkung IO Operationen wie das `console.log` in der funktionalen Welt statt
findet, sehen wir beim Thema Monaten.__


== Funktionen als first class citizen

In der funktionalen Programmierung bilden Funktionen nicht nur einen zentralen Aspekt für Berechnungen,
sondern gelten wie `Values` als so genannte `first class citizens`. Das bedeutet, dass Funktionen ebenfalls
einem Namen zugewiesen werden können und diese Referenzen wie "normale" `Values` als Parameter und
Rückgabewerte behandelt werden können.

In Javascript können Funktionen im `imperativen` Stil definiert werden. Die Funktion kann dann über den
Namen (hier `add`) aufgerufen, aber auch überall eingesetzt werden.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/FirstClassCitizens.js[tags=classic]
----

Funktionen lassen sich in Javascript aber auch in normalen Variablen oder Konstanten speichern.
Im folgenden Beispiel wird die Funktion `add` in der Konstante `fAdd` gespeichert. Die Funktion lässt sich nun über
die Kostante `fAdd` referenzieren und aufrufen.

Der zweiten Konstante `fAdd2` wird eine anonyme Funktion zugewiesen, die mit der verkürzten ES6 Syntax geschrieben ist.
Die Funktion kann nun auch hier über die Konstante `fAdd2` aufgerufen werden.
[source,javascript]
----
include::{sourcedir}/deepdive/functional/FirstClassCitizens.js[tags=f_as_val]
----

Das die in Konstanten gespeicherten Funktionen tatsächlich wie normale Werte behandelt werden können, zeigt die
Funktion `usingAFunction`, die ihrerseits eine Funktion (hier `fAdd` aus dem letzten Beispiel) aufnimmt und ihr
innerhalb ihres Scopes den Namen `addFunction` zuweist, worüber die Funktion aufgerufen werden kann:

[source,javascript]
----
include::{sourcedir}/deepdive/functional/FirstClassCitizens.js[tags=f_as_param]
----

NOTE:  __In den nun folgenden Beispielen werden Funktionen mit der ES6 Syntax definiert. Also z.B.__ `(x, y) => x + y`

== Higher order functions

Da wir in der funktionalen Welt Funktionen als normale Datenelemente betrachten können, ist es auch möglich, Funktionen
anderen Funktionen als Parameter zu übergeben, bzw. neue Funktionen als Ergebnis zurück liefern zu lassen.

Diese Funktionen, welche andere Funktionen verarbeiten können, nennt man *higher order functions (HOF)*.

=== Funktionen als Parameter

Zunächst zeigt folgendes Beispiel, wie eine Funktion als Parameter an eine HOF übergeben werden kann:

Definiert ist eine HOF `mapX`, die einen übergebenen Wert `x` auf eine weitere Funktion `xMapper` anwendet, die
ihrerseits als zweiter Paramter an die HOF übergeben wurde.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/HigherOrderFunction.js[tags=function_parameter]
----

`mapX` wird nun mit zwei Parametern, einer Zahl und einer Funktion, aufgerufen. Die Funktion ist in diesem Fall eine
anonyme Funktion, die nur über den Parameter von `mapX` zu einem Namen gelangt. Solche anonymen Funktionen, die
direkt als Paramter übergeben werden, nennt man auch `Lambda-Ausdrücke`.

Lambda-Ausdrücke sieht man z.B. bei Javascript auch in der normalen Collection-API, wie hier bei einem Array.
Über die Methode `map` wird eine Funktion `i => i + 2` übergeben, die alle Elemente des Arrays um `2` erhöht.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/HigherOrderFunction.js[tags=lib_example]
----

=== Funktionen als Ergebnisse

Nachdem wir nun gesehen haben, wie Funktionen an higher-order-functions als Paramter übergeben werden können, fehlen noch
die Funktionen, welche als Berechnungsergebnisse zurück gegeben werden können.

Als Einstieg haben wir eine HOF `getEqualFunction`, die eine Funktion zum Vergleich zweier Werte zurück
liefert. Rufen wir nun `getEqualFunction` auf, so erhalten wir als Ergebnis eine neue Funktion, die ihrerseits mit zwei
Werten aufgerufen werden kann und den eigentlichen Vergleich macht.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/HigherOrderFunction.js[tags=higher_order_function]
----

Eine HOF, die immer eine fest definierte Funktion zurück gibt macht allerdings nicht viel Sinn. Man könnte so ja
auch die Vergleichsfunktion direkt schreiben. Interessant wird es erst, wenn wir Parameter aus der HOF nehmen, in die
neue Funktion einweben und unsere neue Funktion somit konfigurierbar machen.

Das nächste Beispiel zeigt die HOF `greaterThan`, die einen Paramter `x` annimmt und diesen in eine neue Funktion
einwebt: `(y) => x > y`, welche zurückgegeben wird. Ein Aufrufer kann nun diese den Parameter `y` übergeben, welcher
dann mit dem Wert von `x` aus der Ursprungsfunktion verglichen wird.

Mit diesem Mechanismus können nun beliebig viele Funktionen konfiguriert werden, die immer gegen einen anderen Wert
vergleichen:

[source,javascript]
----
include::{sourcedir}/deepdive/functional/HigherOrderFunction.js[tags=function_builder]
----

== Currying oder Schönfinkeln

In einigen Programmiersprachen oder mathematischen Konstrukten, wie dem ursprünglichen Lamdba-Kalkül, besitzen
Funktionen nur genau einen Eingabewert und einen Rückgabewert. Aus der Praxis kennen wir allerdings nur sehr wenige
Funktionen, die nur einen Eingabeparameter haben, sondern mehere, wie dieses simples Beispiel einer Additionsfunktion.

----
const add = (x, y) => x + y
----

Um diesem Problem zu begegnen formulierten Moses Schönfinkel und Haskell Brooks Curry nacheinander ein Verfahren,
welches auf Funktionen höherer Ordnung setzt um jede Funktion mehrerer Veränderlicher in eine Funktion mit nur noch
einem Parameter umzuwandeln.

Das verfahren haben wir bereits im letzten Teil bei der Funktion `greaterThan` gesehen. Generell gesagt wird
beim Currying aus jeder Funktion

----
(a, b, .. n) => a + b + ... + n
----

die Parameter so umgestellt, dass jede Funktion neben ihrem Parmater eine neue Funktion zurück gibt, die einen
weiteren Parameter verarbeitet:

----
a => b => ... => n => a + b + ... + n
----

NOTE: __Schönfinkel gilt als der eigentliche Erfinder des Verfahrens, Curry formalisierte es aber zuerst formal
      in einer Theorie. Daher spricht man sehr oft von `currying` aber auch von `schönfinkelisation`, bzw. `Schönfinkeln`.
      Schönfinkel hat nur leider den Nachteil im englischen schwerer aussprechbar zu sein wie Curry, sodass meistens
      von `currying` die Rede ist. __

Als konkretes Beispiel schauen wir uns wieder die Additionfunktion an. Aus einer Funktion mit zwei Parametern können
wir nun eine Funktion mit einem Paramater `x` machen, die wiederum eine Funktion mit einem Parameter `y` zurück gibt,
die wiederum beide Werte `x` und `y` addiert.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/Currying.js[tags=currying]
----

Als ein Beispiel für den praktischen Einsatz wollen wir uns eine Environmentsteuerung anschauen. Die Software kann
also in eine `Test` und einem `Prod`-Modus laufen. Dafür definieren wir erst einmal ein `boolean` und zwei `Environments`:

[source,javascript]
----
include::{sourcedir}/deepdive/functional/Currying.js[tags=curry-factory-data]
----

Ein erster Ansatz definiert ein `api`-Objekt als Nutzer des Environments. Das Objekt besitzt die `getCustomer` Funktion,
die ein `environment` und einen `customer` annimmt und einen HTTP Call simuliert. Beim Aufruf der Funktion muss nun
jedesmal das Environment mitgegeben werden. Eine Unterscheidung, ob `Prod` oder `Test`, müsste nun bei jedem Aufruf geschehen.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/Currying.js[tags=curry-factory-oldway]
----

Neben anderen Lösungen, können wir hier aber auch das Currying einsetzen, um die Fallentscheidung, welches Environment
genutzt werden soll, zentral in das `api`-Objekt auszulagern.

Zunächst definieren wir uns eine Curryfunktion `getCustomerCurry`, die als ersten Parameter das environment nimmt und eine
Funktion zurück gibt, welche dann den `customer` annimmt und den "HTTP Call" vollführt.

Das `api` Objekt definiert nun nicht mehr die Funktion direkt, sondern nutzt `getCustomerCurry` um entweder ein
`getCustomer` mit dem `testEnvironment` oder `prodEnvironment` zu definieren. Die Nutzer können nun `getCustomer`
mit dem eigentlichen Customer aufrufen und müssen sich nicht mehr um das Environment kümmern.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/Currying.js[tags=curry-factory]
----

Einen anderen Fall können wir direkt im letzten Beispiel finden. Wir haben das `devMode` Flag direkt im `api`-Objekt
benutzt, obwohl die Variable nicht im Scope von `api` definiert wurde. Diese `Closures` können innerhalb von Funktionen
und auch Objekten sinnvoll sein, in unserem Beispiel haben wir aber "diese Variable die irgendwo definiert ist und da
sie da war, haben wir sie halt genutzt".

Diese Closures können wir auch hier etwas einschränken, in dem wir eine `create`-Funktion um das Objekt legen und `devMode`
als `envMode` Paramter in den Scope eingeben.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/Currying.js[tags=curry-closure]
----

NOTE: __Genau genommen ist das letzte Beispiel kein formal korrektes Currying, da wir anstatt einer neuen Funktion ein
        neues Objekt zurück geben. Und zeigt sich auch, dass die "klassischen" Methoden Code zu refactorn nicht
        mit denen der funktionalen Programmierung kollidieren müssen. Denn ob man das obere Beispiel jetzt unter dem
        Licht eines "angepassten" Curryings oder einer simplen Wrappermethode sieht, sei dem Leser überlassen.__


== Praktische Anwendung

In diesem Kapitel werden einige praktische Anwendungen gezeigt, die die funktionale Programmierung ermöglicht.
Die Beispiele haben nicht den Anspruch einer überragenden Lösung gegenüber anderen, sondern sollen vor Allem die
Einsatzmöglichkeiten des bisher Gezeigten aufzeigen.

=== Repeated Parameters mit Currying und Rekursion

Repeated Parameters sind mittlerweile ein fester Bestandteil in vielen Sprachen für die Übergabe einer beliebigen
Anzahl an Parametern eines beliebigen Typs an Funktionen.

In Java existiert zum Beispiel der `...` Ausdruck, um einen Parameter "repeatable" zu machen. `names` ist dann
lediglich ein Array der Parameter :

[source,java]
----
public void repeatedParameters(String... names) {
    Arrays.stream(names).forEach(System.out::println);
}

repeatedParameters("Hallo", "Welt", "Wie", "Gehts", "Dir");
----

Javascript kennt nun dieses Feature nicht. Wir können uns aber mit den Elementen des Currying und der Rekursion
ein Behelfskonstrukt bauen:

`sum` soll beliebig viele Zahlen addieren. Daher gibt jeder Aufruf von `sum` eine Funktion zurück, die widerum
ihren Parameter `y`, mit von `x` addiert und wieder als ersten Parameter an `sum` rekursiv weitergibt.
Als Abbruchbedingung definieren wir uns ein Terminatorsymbol und nehmen pragmatisch `null`.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//RepeatedParametersCurrying.js[]
----

`sum` lässt sich nun mit beliebig vielen Werten aufrufen.

=== Datenvalidierung mit functional composition

Das nächste Beispiel zeigt, wie wir durch die Kombination aus mehreren Funktionen uns eine Datenvalidierung
konfigurieren können.

Zunächst definieren wir Validierungsfunktionen, die wir per Currying konfigurieren können. Alle bekommen
einen Soll-Wert als ersten Parameter, den Ist-Wert als Parameter der inneren Funktion und vergleichen beide Werte.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//ValidatorWithFunctionalCombination.js[tags=validation]
----

Zusätzlich definieren wir eine Kombinationsfunktion. Diese übernimmt zwei Validatorfunktionen und gibt eine
neue Validierungsfunktion zurück, die `value` auf die beiden Funktionen anwendet und diese UND-verknüpft.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//ValidatorWithFunctionalCombination.js[tags=validation-combination]
----

Nun können wir aus den Validierungsfunktionen und der Kombinationsfunktion einen mehrstufigen Validator bauen.
Zunächst definieren wir uns mit `max`, `min` und `hallo` drei neue Validatoren.

Mit `combine` kombinieren wir nun `max`, `min` und `hallo` zu einem neuen Validator `validator` der alle drei anderen
in sich vereint. Geben wir nun `validator` einen Wert als Parameter wird dieser Wert durch alle drei Einzelvalidatoren
überprüft:

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//ValidatorWithFunctionalCombination.js[tags=validation-usage]
----

=== funktionale Datenstrukturen

Reizen wir die funktionale Programmierung etwas aus, so lassen sich auch allein mit Funktionen Datenstrukturen
definieren.

`selectFirst` ist zunächst eine normale Curry-Funktion mit den Parametern `first` und `second` und gibt immer
`first` zurück.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//DataStructure.js[tags=data_structure-select_first]
----

Das Gegenteil ist `selectSecond`. Genauso wie `selectFirst` nimmt diese Funktion die zwei Parameter entgegen,
gibt aber immer nur `second` zurück.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//DataStructure.js[tags=data_structure-select_second]
----

In der Anwendung sehen beide Funktionen so aus:

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//DataStructure.js[tags=data_structure-select_usage]
----

Nun definieren wir die Funktion `makePair`. Diese Funktion soll uns ein funktionales Tuple von zwei Werten
erzeugen, auf die wir mit den beiden Funktionen `selectFirst` und `selectSecond` zugreifen können.

Diese Funktion nimmt die Werte `first` und `second` an und liefert am Ende eine Funktion zurück, die eine
Zugriffsfunktion annimmt, der die beiden Werte zuegwiesen werden.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//DataStructure.js[tags=data_structure-pair]
----

Mit `makePair` wird zunächst ein Tuple mit den Werten `5` und `6` erzeugt. `pair` repräsentiert nun dieses
konkrete Tuple, ist aber auch geichzeitig eine Funktion.

Geben wir nun `pair` die Funktion `selectFirst`, so wird innerhalb von `pair` der Ausdruck `func(first)(second)`
zu `selectFirst(5)(6)` ausgewertet, welche `5` zurück gibt. Geben wir an `pair` die Funktion `selectSecond`, so
erhalten wie den zweiten Wert des Tuples.

=== funktionale Listen

Denkt man nun den oberen Code etwas weiter, so lassen sich mit `makePair`, `selectFirst` und `selectSecond` auch
funktionale Listen erstellen.

Beginnen wir wieder mit den Zugriffsfunktionen. Wie `selectFirst` und `selectSecond` werden die Funktionen
`head' und `tail` definiert.

`head` definiert sich durch eine Funktion, die einen `value` und einen `tail` entgegennimmt und immer `value` zurück
liefert.

`tail` gibt wiederum immer den Parameter `tail` zurück.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//List.js[tags=functional_list-selectors]
----

Die Liste als solches besteht nun aus einer Funktion, die einen `value` und einen `tail` bekommt und eine Funktion
zurückgibt, die eine Selektionsfunktion `func` annimmt und auf diese `value` und `tail` anwendet.

Anders als bei `makePair` besteht `tail` hier immer aus einer weiteren Liste bis das Ende erreicht ist.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//List.js[tags=functional_list-listfunction]
----

`tail` muss auch irgendwann an ein Ende kommen. Es wird also eine Terminierung benötigt. In diesem Beispiel haben wir
keine harte Terminierung, sondern eine `nil`-Liste, die bei der Anwendung von `head` immer `null` und bei `tail`
immer sich selbst zurück gibt:

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//List.js[tags=functional_list-nil]
----

Mit diesen vier Funktionen können wir nun die Liste nun verwenden. Bei der Verwendung fällt auf, dass wir darüber
hinaus auch eine immutable List entworfen haben. Kleinere Listen lassen sich so problemlos in größere Listen einbetten,
ohne das größere Mengen der Daten kopiert werden müssen.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//List.js[tags=functional_list-usage]
----

Mit dieser konkreten Datenstruktur lassen sich auch weitere Funktionen definieren, die den Zugriff ein wenig erleichtern:


`length` liefert die Länge einer Liste zurück. Per Rekursion wird die Liste durchlaufen, bis `tail` das Terminiderungselement
`nil` ist. Parallel wird ein Counter inkrementiert, der am Ende zurück gegeben wird.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//List.js[tags=functional_list_length]
----

Möchten wir mit den bisherigen Funktionen auf ein Element an einem bestimmten Index zugreifen, müssen wir mit `tail`
so lange die Liste iterieren, bis wir am entsprechenden Element sind. Damit dieser Vorgang nicht immer wiederholt
werden muss, definiert `get` eine Funktion, die rekursiv bis zu dem entsprechenden Element vordringt und das entsprechende
Element zurück gibt.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage//List.js[tags=functional_list_get]
----

In der letzten hier gezeigten Funktion, werden zwei Listen konkateniert. Auch hier wird wieder mit Rekursion gearbeitet.
Ist die erste Liste gleich die leere Liste `nil`, so wird einfach die zweite Liste als Konkatenation zurück.
In jedem anderen Fall wird eine neue Liste zurück gegeben, deren `head` das erste Element der ersten Liste ist und deren
`tail` die Liste, die aus der Konkatenation vom Rest von `list1` und `list2` besteht.

[source,javascript]
----
include::{sourcedir}/deepdive/functional/usage/List.js[tags=functional_list_append]
----


== Monaden

Das Thema Monaden

[source,javascript]
----
include::{sourcedir}/deepdive/functional/monads/Motivation.js[tags=simple_object]
----

[source,javascript]
----
include::{sourcedir}/deepdive/functional/monads/Motivation.js[tags=substitution]
----

[source,javascript]
----
include::{sourcedir}/deepdive/functional/monads/Motivation.js[tags=reality]
----

[source,javascript]
----
include::{sourcedir}/deepdive/functional/monads/Motivation.js[tags=expectation]
----

Hint: None as the 0 in 3 * 4 * 0 * 5 * 6

== Algebraische Datenstrukturen

=== Kleine Motivation

Wir bauen eine Benutzerregistrierung und bedienen uns einem einzelnen Modell.

[source,javascript]
----
include::{sourcedir}/../kotlin/functionalDDD/RegisterCustomer.kt[tags=naiv_customer]
----

Leider bildet dieses Modell nicht die eigentliche Registrierung ab, die auf Events und einem
darauf aufbauenden Workflow basiert:

1. Der Kunde regisriert sich mit einem Vornamen, einem optionalen mittleren Namen, einem Nachnamen,
seiner Emailadresse und einem Passwort. Zusätzlich kann der Kunde eine Einwilligung zur
Datennutzung geben, damit wir BigDataStuff machen können.

2. Bevor der Kunde sein Konto nutzen kann, muss er zunächst seine Emailadresse verifizieren.
Dafür wird eine Email an die angegebene Adresse mit einem Verifizierungstoken geschickt.

3. Nachdem der Kunde seine Emailadresse verifiziert hat, hat der Kunde ein voll nutzbares Konto.

Unser naives Datenmodell verursacht nun einige Probleme:

* Den optionalen Charakter des mittleren Namens
bilden wir nur unzureichend ab. Im Zweifel mit einem `null`, was generell eine eher schlechte Idee ist, da
es ein nicht unerheblicher Seiteneffekt ist, der bei jedem lesenden Zugriff abgefangen werden muss.

* Die `String`-Felder unterscheiden sich nur durch ihren Namen. Nichts könnte uns davon abhalten `firstName = lastName`
oder `lastName = email` zu probieren. Zwar würden wir sowas mit unserem Domänenwissen nicht machen, aber ein neuer
Kollege oder ein anderer Nutzer unseres Modells käme evtl. auf die Idee, dass ein Nachname auch ein Vorname ist.

* Das Emailverifizierungsverfahren bilden wir zur Zeit mit einem `Boolean`-Feld ab. Zwar ist dies eine gültige
Modellierung, allerings wäre der Umstand einer verifizierten Email besser direkt im Emailmodell aufgehoben.

* Das Passwort wird zunächst im Klartext übermittelt und im Modell abgebildet. Allerdings sollten wir dies nicht zu lange
tun, um mögliche Angiffsvektoren zu minimieren. Eine frühe Verschlüsselung ist also angebracht. Im naiven Ansatz
speichern wir zunächst das Klartestpasswort in einem Feld, welches wir im späteren Verlauf verschlüsseln und das Feld
`passwordHash` setzen, wobei wir sicher gehen müssen, `password` auf `null` oder Ähnliches zu setzen.

Wir wollen nun einen funktionalen Ansatz betrachten, mit dem wir einige dieser Probleme aus dem Weg oder zumindest
handhabbarer gestalten können.

=== Typen im funktionalen Sinne

In funktionalen Sprachen sind Typen nicht das selbe wie z.B. Klassen in einer objektorientieren Sprache. Typen sind
in erster Linie Namen für eine Anzahl möglicher Werte.

So kann der Typ `Boolean` lediglich zwei Werte annehmen: `true` und `false`. Der Typ `Int` kann dagegen die Werte
`-2147483648` bis `2147483647` annehmen. `String` dagegen kann für eine definierte Anzahl an Zeichen, beliebig
viele Permutationen annehmen. Wir können uns auch eigene, neue Typen definieren, die ebenfalls auf einer definierten
Anzahl möglicher Werte basieren.

Kotlin ist zwar keine rein funktionale Sprache, wir können aber auch hier einige Konzepte anwenden. Zunächst ist
es relativ simpel, einen neuen Typ einzuführen, der auf einem anderen Typ basiert. Zwar bedienen wir uns hier dem
Konstrukt der Klasse, unsere Typen haben aber eher die Interpretation eines Typalias, oder einem unterscheidbaren
"Vetter" des Basistypes.

Allein mit dem folgenden Beispiel haben wir uns einen Vorteil geschaffen, in dem wir einen `Name` von einem `Lastname`
unterscheidbar gemacht haben. Ein `name: Name = lastName: Lastname` ist somit nicht möglich. Ein Umstand, der uns
ggf. einige Unittests ersparen dürfte.

----
include::{sourcedir}/../kotlin/functionalDDD/Types.kt[tags=simple_types]
----

=== AND Types



[source,javascript]
----
include::{sourcedir}/../kotlin/functionalDDD/Types.kt[tags=and_types]
----

=== OR Types
[source,javascript]
----
include::{sourcedir}/../kotlin/functionalDDD/Types.kt[tags=or_types]
----

=== Beispiel einer Registrierung

Basistypen:
[source,javascript]
----
include::{sourcedir}/../kotlin/functionalDDD/BaseTypes.kt[tags=base_types]
----

Optionale Parameter:
[source,javascript]
----
include::{sourcedir}/../kotlin/functionalDDD/BaseTypes.kt[tags=option]
----

Datenvalidierung und Werterzeugung:
[source,javascript]
----
include::{sourcedir}/../kotlin/functionalDDD/Validation.kt[tags=validation]
----

Aussagekrätigere Fehlerbehandlung
[source,javascript]
----
include::{sourcedir}/../kotlin/functionalDDD/Validation.kt[tags=explicit_error_handling]
----

Email-Workflow:
[source,javascript]
----
include::{sourcedir}/../kotlin/functionalDDD/EmailAddress.kt[tags=email_addresses]
----

[source,javascript]
----
include::{sourcedir}/../kotlin/functionalDDD/EmailAddress.kt[tags=email_confirmation]
----

Typed Customer:

[source,javascript]
----
include::{sourcedir}/../kotlin/functionalDDD/RegisterCustomer.kt[tags=typed_customer]
----



https://dgronau.wordpress.com/2011/02/03/funktoren-in-java/

https://entropia.de/images/6/63/20100613-monaden.pdf

https://dzone.com/articles/whats-wrong-java-8-currying-vs

Functional Programming through Lambda Calculus - Greg Michaelson, 2011

Domain Modelling mage Functional - Scott Wlaschin, 2018