:sourcedir: ../java

= Das Java Typsystem und wo es sich nur für eins hält.

Wie in jeder anderen höheren Programmiersprache, so hampelt man auch bei Java nicht mehr direkt auf den Speicherblöcken des
Rechners rum, sondern hat eine Abstraktion, welche einem die Arbeit erleichert. Damit nun aber die einzelnen Bytes richtig
interpretiert werden können, benötigen wir Typen und ein Typsystem.

== Primitive
Java bezeichnet sich selbst zwar als objektorientierte Sprache, ganz genau stimmt das aber nicht. Neben den eigentlichen
Objekten, besitzt Java ebenfalls Primitivtypen, wie `int`, `double` und `char`, welche weder Methoden besitzen, noch
andere Attribute als ihren inhärenten Wert.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Primitives.java[tags=without_class]
----

Eine Sonderrolle nehmen dabei Arrays ein. Arrays bilden die einzige native Collection, welche direkt in der JVM abgebildet
wird, also nicht mit Sprachkonstrukten nachgebaut wird. Arrays speichern neben eigentlichen Werten auch immer den Typ
mit, um den 

Neben jedem Primitivtyp existiert eine dazugehörige Wrapperklasse, welche z.B ein `int` etwas objektorientieter macht und
so zum Beispiel für Collectionklassen verfügbar macht.


[source,java]
----
include::{sourcedir}/deepdive/typesystem/Primitives.java[tags=autoboxing]
----