:sourcedir: ../java

= Das Java Typsystem und wo es sich nur für eins hält.

Wie in jeder anderen höheren Programmiersprache, so hampelt man auch bei Java nicht mehr direkt auf den Speicherblöcken des
Rechners rum, sondern hat eine Abstraktion, welche einem die Arbeit erleichert. Damit nun aber die einzelnen Bytes richtig
interpretiert werden können, benötigen wir Typen und ein Typsystem.

== Primitive und Literale
Java bezeichnet sich selbst zwar als objektorientierte Sprache, ganz genau stimmt das aber nicht. Neben den eigentlichen
Objekten, besitzt Java ebenfalls Primitivtypen, wie `int`, `double` und `char`, welche weder Methoden besitzen, noch
andere Attribute als ihren inhärenten Wert.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Primitives.java[tags=without_class]
----

Eine Sonderrolle nehmen dabei Arrays ein. Arrays bilden die einzige native Collection, welche direkt in der JVM abgebildet
wird, also nicht mit Sprachkonstrukten nachgebaut wird. Arrays speichern neben eigentlichen Werten auch immer den Typ
mit, um den Speicherverbrauch für die JVM berechnen zu können.

== Autoboxing
Neben jedem Primitivtyp existiert eine dazugehörige Wrapperklasse, welche z.B ein `int` etwas objektorientieter macht und
so zum Beispiel für Collectionklassen oder generell für Generics verfügbar macht.

Seit Java 5 muss man auch die
Primitivtypen nicht mehr explizit auf diese Wrapperklassen casten, sondern kann sich diese Aufgabe vom Javacompiler
übernehmen lassen:


[source,java]
----
include::{sourcedir}/deepdive/typesystem/Primitives.java[tags=autoboxing]
----
Dabei ist es unerheblich, ob man die Zuweisung zu einer Variable oder den Wert als Parameter einer Methode übergibt.

*Aber*: Das Autoboxing ist leider nicht ganz zu Ende gedacht. Schaut man sich folgendes Beispiel an, so würde man
erwarten, dass das `2` Literal wie im oberen Beispiel zu einem `Integer` konvertiert und sodann an den `instanceof`
Operator übergeben wird. Dem ist aber nicht so. Literale bleiben in dieser Konstruktion immer ihrem Primitivtyp treu.
Hier wird also `false` ausgegebem.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Primitives.java[tags=autoboxing_strange]
----

== Klassen
Hier wird es objektorientiert.

Der Kern des Java Typsystems besteht aus Klassen und Objekten und die Abhängigkeiten und Hierarchieren dazwischen. Als
Basis gilt die allen Klassen gemeinsame Oberklasse `Object`.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Classes.java[tags=classes]
----

Hier sehen wir auch direkt wieder eine Besonderheit bei den Literalen. Ein Stringliteral ist immer vom Typ `String`, ist
also ein Objekt. So ist denn auch folgender Ausdruck valide `"Hallo".toString()` und auch das vorangegangene Beispiel
klappt mit einem Stringliteral `"Hallo" instanceof Object`.