:sourcedir: ../java

= Final, Volatile, Transient und Synchronized - Was, Wozu und Warum?


== Ganz schnell: Transient
`transient` ist ein Marker für Variablen, welche bei einer Serialisierung ignoriert werden sollen. Lange vor Json,
Jackson und `@JsonIgnore`-Annotations konnte man bereits dort Objekte partiell serialisieren.

[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/Transient.java[tags=class]
----


Wird die Transientvariable nun serialisiert und wieder deserialisiert, hat `value2` den Wert `null`.

 Vorher  : Transient{value1='Hallo', value2='Welt'}
 Nachher : Transient{value1='Hallo', value2='null'}

`transient` funktioniert übrigens auch wunderbar mit einer Json-Serialisierung mit Jackson und kann als "native"
Alternative zu `@JsonIgnore` genutzt werden.

== Object lifecycle
[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/Lifecycle.java[tags=class]
----

== Nun: Final als Konstanten

Final als konstanter Wert. Jede Variable wird nur genau einmal gesetzt und kann nicht überschrieben werden.

[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/FinalConstant.java[tags=aConstantFinalValue]
----


Final im Kontext eines Klassenattributs. Diese können dabei im Klassenkontext oder im Konstuktor initialisiert
werden, da dieser bei der Objekterzeugung aufgerufen wird. Andere Methoden sind tabu.

[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/FinalConstant.java[tags=constructor]
----

So, das war noch recht einfach. Nun als kleine Grundlage für die nächsten Themen:

            
== Das Java Memory Model (JMM)

Das JMM ist eine Abstraktion des darunter liegendenden, plattformabhängigen Hardwaremodells.

 +---------------------------+
 |     Java memory model     |
 +---------------------------+
 +---------------------------+
 |   Hardware memory model   |
 +---------------------------+


Im Modell hat jeder Thread seine eigene Ausführungseinheit und besitzt einen Speichercache. Die Hardware hat hier mit
Level 1, 2 und 3 Caches, Hyperthreading etc. ein wesentlich komplexeres Modell, vor dem uns die JVM ein bisschen schützen will.

    THREAD1                                    THREAD2
+-------------+                            +-------------+
|             |       +------------+       |             |
|  +-------+  |       |    MAIN    |       |  +-------+  |
|  |  CPU  |  |       |   MEMORY   |       |  |  CPU  |  |
|  +-------+  |       |            |       |  +-------+  |
|             |       +------------+       |             |
|  +-------+  |             ║              |  +-------+  |
|  | CACHE |  |             ║              |  | CACHE |  |
|  +-------+  |             ║              |  +-------+  |
|            <══════════════╩═══════════════>            |
+-------------+            bus             +-------------+

Beim Threadstart lädt sich dieser alle notwendigen Daten aus dem Hauptspeicher in seinen Cache und benutzt
zum Abgleich der Daten zwischen Cache und Hauptspeicher zwei Operationen:

* `flush` Änderungen im Cache werden in den Hauptspeicher zurück geschrieben.
* `refresh` Aktuelle Daten aus dem Hauptspeicher wird in den Cache geladen.

Wann `flush` und `refresh` stattfinden bedingen die Regeln des JMM. Das bedeutet für uns, dass Änderungen,
die ein Thread an seinen Daten vornimmt, nicht unbedingt sofort in den Hauptspeicher zurückgeschrieben werden.

Damit stellen sich uns aufgrund dieses Modells einige Fragen:

* _Atomicity_: *Welche Operationen sind atomar, d.h. werden nicht durch andere Threads unterbrochen?* +
             Threads werden unterbrochen um Platz für andere Threads zu machen. Manche Operationen brauchen aber einen
             unterbrechungsfreien Ablauf.

* _Ordering_: *In welcher Reihenfolge passieren die Aktionen?* +
            Die Reihenfolge in der ein Tread seine Aktionen abarbeitet muss nicht zwangsläufig von einem anderen Thread
            in dieser Reihenfolge gesehen werden. Compiler, Optimizer, CPUs machen gerne Reorderings, um performanter
            Aktionen auszuführen. Partielle flushs, welche nur einen Teil der Änderungen auf einmal postulieren tun
            ihr übrigens.

* _Visibility (Sequential Consistency)_: *Wann werden Modifikationen im Speicher anderen Threads sichtbar gemacht?*
            Durch die `flush` und `refresh` Operationen, sehen andere Threads Änderungen an gemeinsam genutzten Variablen
            ggf. sehr viel später.


Beispiele:
[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/JmmPitfalls.java[tags=jmm]
----

* `number`: Ein long mit 64bit Länge. Auf 32 bit Systemen kann es passieren, dass beim Lesen nur die Hälfte des Werts
          gesetzt ist. -> _Atomicity_
* `flag`: Die JVM garantiert uns für ein Boolean immer einen atomaren Zugriff. Soweit so gut.
          Problem gelöst! Allerdings ist hier noch lange nicht gesagt, dass der Wert auch aus dem Cache von `Thread1`
          geflusht wurde. `Thread2` kann noch immer `false`sehen. -> _mangelnde Sequential Consistency_
* `read`: Die Methode geht davon aus, dass zuerst die long-Variable und dann erst das flag auf true gesetzt wurde.
          Wenn also die if-Bedingung erfüllt ist, geben wir immer den richtigen Wert auf der Konsole aus? Oh... Doch nicht.
          Beim Flush von `Thread1` in den Hauptspeicher und dem refresh von `Thread2` kann es passieren, dass beide
          Anweisungen gedreht werden, sodass `flag` bereits `true` ist, number aber noch `0L` ist. -> _Reordering_


== Final im nebenläufigen Umfeld

In folgender Klasse werden zwei Werte definiert. Eine ist final, die andere nicht. Im ersten Thread und damit in seinem
Cache wird der Konstruktor aufgerufen und die Werte gesetzt.

`Thread2` wiederum hat nun das Problem der _Sequential Consistency_. Aber wann werden jetzt die Variablen `f`, `x` und
`y` von Thread1 in den Hauptspeicher geflusht? Für `f` ist es dabei noch relativ egal, da wir die Nichtexistenz des Objekts
bereits im Code behandeln. Aber wenn wir beim Auslesen in `Thread2` auf einmal `f` sehen, `x` und `y` aber noch nicht
geflusht wurden, kann es zu unvorhergesehenen Ereignissen kommen.

Hier hilft nun das `final`. Da einer `final`-Varible immer genau einmal ein Wert zugewiesen werden muss, wird bei genau
dieser Zuweisung ein partieller `flush` ausgeführt und die Variable wird im gesamten Speicher propagiert.
Für `Thread2` bedeutet das, wann immer ein lesender Zugriff auf eine `final`-Variable geschieht, gearaniert uns das JMM,
dass der Wert aktuell und korrekt ist. Für `y` gilt diese Regel allerdings nicht. Hier kann es passieren, dass bei einem
lesenden Zugriff der Wert noch 0 ist, obwohl das umgebende Objekt bereits sichtbar ist.

[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/FinalConcurrent.java[tags=class]
----

== Volatile - Der kleine Bruder von synchronized

Das Problem der mangelnden Sequential Consistency bei Konstanten hat uns im vorigen Beispiel das `final`abgenommen.
Was ist nun aber mit den vielen nicht konstanten Werten, die sich während der Laufzeit des Programms fortwährend ändern?

*Am besten gar nicht erst zulassen und mit so vielen immutable Objekten arbeiten wie möglich. ;-)*

Aber wenn man nun doch ein shared value zwischen zwei oder mehreren Threads hat, so hilft einem `volatile`, die
Sequential Consistency aufrechtzuerhalten.

[source,java]
----
include::{sourcedir}/deepdive/final_transient_volatile/Volatile.java[tags=class]
----





