:sourcedir: ../java

= Teil 2 : Das Java Typsystem und wo es sich nur für eins hält.

Wie in jeder anderen höheren Programmiersprache, so hampelt man auch bei Java nicht mehr direkt auf den Speicherblöcken des
Rechners rum, sondern hat eine Abstraktion, welche einem die Arbeit erleichert. Damit nun aber die einzelnen Bytes richtig
interpretiert werden können, benötigen wir Typen und ein Typsystem.

== Primitive und Literale
Java bezeichnet sich selbst zwar als objektorientierte Sprache, ganz genau stimmt das aber nicht. Neben den eigentlichen
Objekten, besitzt Java ebenfalls Primitivtypen, wie `int`, `double` und `char`, welche weder Methoden besitzen, noch
andere Attribute als ihren inhärenten Wert.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Primitives.java[tags=without_class]
----

Eine Sonderrolle nehmen dabei Arrays ein. Arrays bilden die einzige native Collection, welche direkt in der JVM abgebildet
wird, also nicht mit Sprachkonstrukten nachgebaut wird. Arrays speichern neben eigentlichen Werten auch immer den Typ
mit, um den Speicherverbrauch für die JVM berechnen zu können.

== Autoboxing
Neben jedem Primitivtyp existiert eine dazugehörige Wrapperklasse, welche z.B ein `int` etwas objektorientieter macht und
so zum Beispiel für Collectionklassen oder generell für Generics verfügbar macht.

Seit Java 5 muss man auch die
Primitivtypen nicht mehr explizit auf diese Wrapperklassen casten, sondern kann sich diese Aufgabe vom Javacompiler
übernehmen lassen:


[source,java]
----
include::{sourcedir}/deepdive/typesystem/Primitives.java[tags=autoboxing]
----
Dabei ist es unerheblich, ob man die Zuweisung zu einer Variable oder den Wert als Parameter einer Methode übergibt.

*Aber*: Das Autoboxing ist leider nicht ganz zu Ende gedacht. Schaut man sich folgendes Beispiel an, so würde man
erwarten, dass das `2` Literal wie im oberen Beispiel zu einem `Integer` konvertiert und sodann an den `instanceof`
Operator übergeben wird. Dem ist aber nicht so. Literale bleiben in dieser Konstruktion immer ihrem Primitivtyp treu.
Hier wird also `false` ausgegebem.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Primitives.java[tags=autoboxing_strange]
----

== Klassen
Hier wird es objektorientiert.

Der Kern des Java Typsystems besteht aus Klassen und Objekten und die Abhängigkeiten und Hierarchieren dazwischen. Als
Basis gilt die von allen Klassen abgeleitete Oberklasse `Object`. Ein allen Klassen gemeinsamer Bottomtype existiert nicht.

[source,java]
----
include::{sourcedir}/deepdive/typesystem/Classes.java[tags=classes]
----

Hier sehen wir auch direkt wieder eine Besonderheit bei den Literalen. Ein Stringliteral ist immer vom Typ `String`, ist
also ein Objekt. So ist denn auch folgender Ausdruck valide `"Hallo".toString()` und auch das vorangegangene Beispiel
klappt mit einem Stringliteral `"Hallo" instanceof Object`.

== Was ist mit null und void ?

In jedem formalen System ist es meist förderlich immer auch das Nullelement zu definieren. In der Mathematik kamen
als erstes die arabischen Gelehrten auf die Idee, mit der uns heute selbstverständlichen `0` die Leere zu formalisieren.
Ein damals nicht alltäglicher Begriff, schaut man sich zum Beispiel das römischen Zahlensystem an, in dem man ein leeres
Element vergeblich sucht. Auch in formalen Sprachen ist es daher sinnvoll, ein leeres oder Nullelement zu definieren, um
die Nichtexistenz eines Elements zu signalisieren. In Java gibt es dafür die zwei Schlüsselwörter: `null` und `void`.

=== null
`null` ist die Nullreferenz. Ein Ausdruck `Object o = null;` definiert also eine Referenz `o`, welche auf `null` zeigt, also
keinen Wert besitzt. Leider war das eine nicht ganz durchdachte Entscheidung der Javaväter und -mütter. Millionen und Abermillionen
Zeilen `if(o != null)` sind somit entstanden. Modernere Konzepte wie `Optional`-Monaden oder Kotlins `nullable`-Types versuchen
diesem Problem Herr zu werden.

Was ist nun `null` eigentlich? Betrachtet man `null` vom Typsystem aus, so fragt man sich, welchen Platz `null` darin einnimmt.
Eine `0` ist ja eine Zahl wie `1` oder `2`. Eine leere Menge `{}` ist genauso eine Menge wie `{'Apfel', 'Birne'}` und alle
Operationen aus ihrem jeweiligen System lassen sich auf sie anwenden. `0 + 1` ist ebenso valide wie `{} ∪ {'Apfel'}`.


Nun. `null` ist schon mal kein Primitivtyp. Folgender Ausdruck ist daher nicht gültig:
[source,java]
----
include::{sourcedir}/deepdive/typesystem/NullAndVoid.java[tags=null_not_a_primitive]
----


Wenn `null` nun also kein Primitivtyp ist, ist es dann eine Art Objekt? Also vielleicht ein Nullobjekt, welches
auf jede Referenz passt?

[source,java]
----
include::{sourcedir}/deepdive/typesystem/NullAndVoid.java[tags=null_not_an_object]
----
Leider zeigt sich auch hier, dass `null` auch kein Obekt ist. Eine Referenz vom Typ `Objekt`, die den Wert
`null` enthält, ist kein Objekt. `null` ist also ganz simpel eine Nullreferenz und ist leider mit dem Typsystem
nicht zu vereinen.

=== Void

Anders als `null` findet man das Wort `void` oft als Rückgabewerten von Methoden vor. Und auch nur dort kann es
der Syntax her eingesetzt werden. Allerdings haben hier die Javaentwickler daneben eine `Void`-Klasse eingeführt
mit der etwas unbefriedigenden Beschreibung:

  The {@code Void} class is an uninstantiable placeholder class to hold a
  reference to the {@code Class} object representing the Java keyword
  void.

Und tatsächlich