spring:
  application:
    name: "java-starter"
    version: 1.0
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    password: "egal"
    username: "egal"
          
server:
  port: 8080
